obj-m += multiplier.o

all:
	make -C /home/ugrads/a/alordonez1/ECEN449/lab-5/lab-5/linux-3.14 M=$(PWD) modules

clean:
	make -C /home/ugrads/a/alordonez1/ECEN449/lab-5/lab-5/linux-3.14 M=$(PWD) clean
